### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by skynet** [corley/dbal-influxdb#2]
Wanted to use this abstraction layer library but it seems to be in a very early development stage. Can you write more documentation on it.

**Comment by wdalmut** [comment]
Yes,

we should, actually we are discussing about the Query Builder, in your opition this feature could be useful? Somebody says that using the Doctrine DBAL as the base layer is quita a bit an overkill...

**Comment by wdalmut** [comment]
ops

**Comment by skynet** [comment]
Not for applications that make use of other Doctrine modules. I would definitely pick Doctrine, instead of ZF. Talking about overkill ...

**Comment by skynet** [comment]
Closing this, since it didn't go anywhere. Maybe another time.
